name: Game Documentation
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: 
  contents: read
  pages: write
  deployments: write
  id-token: write

jobs:
  docs:
    runs-on: windows-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Check Installed Software
        run: where git & where python & where pip
        shell: cmd
        
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: 'recursive'

      - name: Install Conan
        run: pip install conan

      - name: Install Doxygen
        run: conan download doxygen/1.17.0@#7bbd9853ee4859042bea8683d68e418e:9f839a3d76e1fd667acf68381254d811321c9026 --remote conancenter
        
      - name: Run Doxygen
        run: doxygen devops\docs\Doxyfile
        
      - name: Upload Docs
        uses: actions/upload-pages-artifact@v5
        with:
          path: Documentation\html
          
      - name: Setup Pages
        uses: actions/configure-pages@v6
        
      - name: Deploy To GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
